name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:  # 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: MANUJULDO17 
          output: dist/snake.svg

      - name: Commit and push the generated snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated snake animation"
          add: "dist/snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
